import { Poppins } from "next/font/google";
import "../app/weather/global.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-slate-800`}>{children}</body>
    </html>
  );
}
